# Generated by Django 3.1.7 on 2021-03-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_registration', models.DateField()),
                ('business_type', models.CharField(choices=[('For Profit', 'For Profit'), ('Not For Profit', 'Not For Profit')], default='Not For Profit', max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('sub_county', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('amount_invested', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('source_of_income', models.CharField(max_length=30)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_branch', models.CharField(max_length=20)),
                ('bank_account_number', models.PositiveIntegerField()),
                ('bank_telephone', models.CharField(max_length=20)),
                ('bank_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='investors/%Y/%m/%d/')),
                ('surname', models.CharField(max_length=20)),
                ('given_name', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('sub_county', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('amount_invested', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('source_of_income', models.CharField(max_length=30)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('kin_surname', models.CharField(max_length=20)),
                ('kin_given_name', models.CharField(max_length=20)),
                ('kin_occupation', models.CharField(max_length=20)),
                ('kin_telephone', models.CharField(max_length=20)),
                ('kin_district', models.CharField(max_length=20)),
                ('kin_county', models.CharField(max_length=20)),
                ('kin_sub_county', models.CharField(max_length=20)),
                ('kin_village', models.CharField(max_length=20)),
                ('kin_address', models.CharField(max_length=30)),
                ('kin_email', models.EmailField(max_length=254)),
                ('kin_note', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_branch', models.CharField(max_length=20)),
                ('bank_account_number', models.PositiveIntegerField()),
                ('bank_telephone', models.CharField(max_length=20)),
                ('bank_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('given_name', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('sub_county', models.CharField(max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.institution')),
            ],
        ),
    ]
