# Generated by Django 3.1.7 on 2021-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
