# Generated by Django 3.1.7 on 2021-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20210322_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='bank_account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='bank_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='bank_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
